#!/usr/bin/env bash

set -e

# Print out a classpath that includes guacamole and all of its transitive dependencies, for use by downstream scripts.
#
# First, check for an already-built assembly JAR; if one exists, print its path and exit.
#
# Otherwise, see if a Guacamole JAR (including shaded guava+breeze but no other dependencies) exists.
#
#   if so: pair it with either a "deps" JAR, if one exists, or a classpath built by the Maven dependency plugin
#          otherwise.
#   if not: fail.
#
# If the "-t" argument is provided, test-classes will be included on the classpath as well.

scripts_dir="$(dirname "${BASH_SOURCE[@]}")"

# Load `find_jars` function.
source "$scripts_dir/.jars-rc"
find_jars

cp=
if [ -z "$deps" ]; then
  cp="$main_jar"
else
  # Likewise, "guac" and "deps" jars.
  cp="$main_jar,$deps"
fi

echo "$cp"
