#!/usr/bin/env bash

# Some of our tests require a human reference genome, which is too big to
# distribute. As a workaround we generate a "partial" fasta containing just the
# regions of the reference needed. We check in this partial fasta into the repo
# and it is used by the tests. The command here regenerates these fastas given
# commandline arguments for local paths to the full hg19 and v37 reference
# genomes.

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 /path/to/ucsc.hg19.fasta /path/to/human_g1k_v37.fasta"
    exit 1
fi

HG19_FULL_FASTA_PATH="$1"
GRCH37_FULL_FASTA_PATH="$2"
MAIN_CLASS=org.hammerlab.guacamole.main.GeneratePartialFasta

if [ -z "${GUACAMOLE_JAR}" ]; then
    jar="$(ls -tc target/guacamole-with-dependencies-*.jar | head -n 1)"
    if [ -z "$jar" ]; then
        echo "Couldn't find a Guacamole jar in the target/ directory."
        echo "Are you in the root directory of the Guacamole repo, and have you built Guacamole?"
        echo "To build, run: "
        echo "    mvn package -DskipTests=true"
        echo "    mvn test-compile"
        exit 1
    fi
    echo "Using most recently modified jar: $jar"
else
    jar="${GUACAMOLE_JAR}"
    echo "Using GUACAMOLE_JAR=$jar"
fi

set -e
set -x

full_jar="$jar:target/scala-2.10.5/test-classes"

# HG19 reference
time java -Xmx4g -XX:MaxPermSize=512m "-Dspark.master=local[1]" -cp "$full_jar" "$MAIN_CLASS" \
    --reference-fasta "$HG19_FULL_FASTA_PATH" \
    --output src/test/resources/hg19.partial.fasta \
	--bam-reader-api hadoopbam \
	--padding 180 \
    src/test/resources/cancer-wgs1/*.bam \
    src/test/resources/rna_chr17_41244936.sam

# b37 reference
time java -Xmx6g -XX:MaxPermSize=512m "-Dspark.master=local[1]" -cp "$full_jar" "$MAIN_CLASS" \
    --reference-fasta "$GRCH37_FULL_FASTA_PATH" \
    --output src/test/resources/grch37.partial.fasta \
    src/test/resources/synthetic.challenge.set1.*.sam \
    src/test/resources/tumor.chr20.tough.sam \
    src/test/resources/normal.chr20.tough.sam \
    src/test/resources/tumor.chr20.simplefp.sam \
    src/test/resources/normal.chr20.simplefp.sam \
    src/test/resources/gatk_mini_bundle_extract.bam

