#! /bin/bash
# Convenience script for users of Mount Sinai's demeter cluster.
# Executes the most recently modified guacamole jar with arguments for running on demeter through yarn.
#
# $GUACAMOLE_JAR is defined, then will execute that jar. 
#
# Example invocation:
#
# scripts/guacamole-demeter threshold \
# 	-reads hdfs://demeter-nn1/user/ahujaa01/ftp-trace.ncbi.nih.gov/1000genomes/ftp/data/HG00096/alignment/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam \
#	 -out hdfs://demeter-nn1/user/odonnt02/threshold.gt.adam
#
set -e
set -x

echo "$@" >> ~/.guacamole.invocations.log

if [ -z "${GUACAMOLE_JAR}" ]; then
    jar=$(ls -tc target/guacamole-?.*.jar | head -n 1)
    echo "Using most recently modified jar: $jar"
else
    jar=${GUACAMOLE_JAR}
    echo "Using GUACAMOLE_JAR=$jar"
fi

# Function to get the absolute path of a file:
abspath () { case "$1" in /*)printf "%s\n" "$1";; *)printf "%s\n" "$PWD/$1";; esac; }
jar_abs=$(abspath $jar)

export SPARK_JAVA_OPTS="-Dspark.default.parallelism=1024 -Dspark.shuffle.consolidateFiles=true -Xmx8g -Dspark.speculation=true"

#Set SPARK_HOME
source /etc/spark/conf/spark-env.sh

# Grap Yarn dependencies and put them on the classpath
CLASSPATH=`$SPARK_HOME/bin/compute-classpath.sh`

SPARK_JAR=/opt/cloudera/parcels/CDH/lib/spark/assembly/lib/spark-assembly_2.10-0.9.0-cdh5.0.0-hadoop2.3.0-cdh5.0.0.jar
export SPARK_JAR
SPARK_YARN_APP_JAR=$jar_abs
export SPARK_YARN_APP_JAR

# What should we set this at?
SPARK_WORKER_INSTANCES=1000
export SPARK_WORKER_INSTANCES

# 8g is the maximum, What should we set this at?
SPARK_WORKER_MEMORY=7g
export SPARK_WORKER_MEMORY

exec time java -cp $CLASSPATH:$jar_abs -Xmx8g -XX:MaxPermSize=4g org.bdgenomics.guacamole.Guacamole \
    "$@" \
    -spark_master yarn-client \
    -spark_jar $jar_abs

