#!/usr/bin/env bash

set -e

# Wrapper around spark-shell that puts Guacamole JAR(s) on the classpath.

scripts_dir="$(dirname "${BASH_SOURCE[0]}")"

source "$scripts_dir/.jars-rc"
find_jars

# Build a spark properties file and set the variable $conf_file to its path.
source "$scripts_dir/.spark-rc"

# spark-shell leaves these laying around and they often cause problems during shell-boot.
rm -rf metastore_db derby.log

"$SPARK_HOME"/bin/spark-shell --jars "$main_jar,$deps" --properties-file "$conf_file" "$@"
