#! /bin/bash
# Convenience script for users of Mount Sinai's demeter cluster.
#
# Executes the most recently modified guacamole jar with arguments for running on demeter.
#
# If $GUACAMOLE_JAR is defined, then will execute that jar. 
#
# Example invocation:
#
# scripts/guacamole-demeter threshold \
# 	-reads hdfs://demeter-nn1/user/ahujaa01/ftp-trace.ncbi.nih.gov/1000genomes/ftp/data/HG00096/alignment/HG00096.mapped.ILLUMINA.bwa.GBR.low_coverage.20120522.bam \
#	 -out hdfs://demeter-nn1/user/odonnt02/threshold.gt.adam
#
set -e
set -x

echo "$@" >> ~/.guacamole.invocations.log

if [ -z "${GUACAMOLE_JAR}" ]; then
    jar=$(ls -tc target/guacamole-?.*.jar | head -n 1)
    echo "Using most recently modified jar: $jar"
else
    jar=${GUACAMOLE_JAR}
    echo "Using GUACAMOLE_JAR=$jar"
fi
# Function to get the absolute path of a file:
abspath () { case "$1" in /*)printf "%s\n" "$1";; *)printf "%s\n" "$PWD/$1";; esac; }
jar_abs=$(abspath $jar)

# To turn on debugging on the driver, uncomment this:
# DEBUGGER_JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044"
export SPARK_MEM=36G
export SPARK_JAVA_OPTS="$DEBUGGER_JAVA_OPTS -Dspark.default.parallelism=1024 -Dspark.shuffle.consolidateFiles=true -Xmx8g -Dspark.speculation=true"
exec time java $SPARK_JAVA_OPTS -XX:MaxPermSize=4g -jar $jar_abs \
	"$@" \
	-spark_master spark://demeter-mgmt1.demeter.hpc.mssm.edu:7077 \
	-spark_jar $jar_abs

