#! /bin/bash
# Executes the most recently modified guacamole jar. Run this from the guacamole root directory.

exec time java -Xmx2g -XX:MaxPermSize=512m -jar $(ls -tc target/guacamole-?.*.jar | head -n 1) "$@"
