#!/usr/bin/env bash

# Print path to a built Guacamole JAR (with shaded Guava) in this repo, if one exists, else exit unsuccessfully.

set -e

# Go to the repo root.
cd "$(dirname "$(dirname "${BASH_SOURCE[@]}")")"

scripts/find-jar guac
