#!/usr/bin/env bash
# Executes the most recently modified guacamole jar. Run this from the guacamole root directory.
#
# If $GUACAMOLE_JAR is defined, then will execute that jar. 
#
echo "$@" >> ~/.guacamole.invocations.log

if [ -z "${GUACAMOLE_JAR}" ]; then
    GUACAMOLE_JAR="$(ls -tc target/guacamole-*.jar | grep -v deps | head -n 1)"
    if [ -z "$GUACAMOLE_JAR" ]; then
        cat 1>&2 << EOF
Couldn't find a Guacamole jar in the target/ directory.
Are you in the root directory of the Guacamole repo, and have you built Guacamole?
To build, run:
    mvn package -DskipTests=true"
EOF
        exit 1
    fi
    echo "Found guac jar: $GUACAMOLE_JAR"
else
    echo "Using GUACAMOLE_JAR=$GUACAMOLE_JAR"
fi

if [ -z "$GUACAMOLE_DEPS_JAR" ]; then
  GUACAMOLE_DEPS_JAR="$(ls -tc target/guacamole-deps-only-*.jar | head -n 1)"
  if [ -z "$GUACAMOLE_DEPS_JAR" ]; then
        cat 1>&2 << EOF
Couldn't find a Guacamole deps jar in the target/ directory.
Are you in the root directory of the Guacamole repo, and have you built Guacamole?
To build, run:
    mvn package -DskipTests=true"
EOF
        exit 1
  fi
else
  echo "Using GUACAMOLE_DEPS_JAR=$GUACAMOLE_DEPS_JAR"
fi

exec time java -Xmx4g -XX:MaxPermSize=512m "-Dspark.master=local[1]" -cp "$GUACAMOLE_JAR:$GUACAMOLE_DEPS_JAR" org.hammerlab.guacamole.Main "$@"

