#!/usr/bin/env bash

if [ -z "$JAR" ]; then
	sha="$(git --no-pager log --no-walk --format="%h" HEAD)"
	export JAR="gs://hammerlab-lib/guacamole-$sha.jar"
fi

export MAIN=org.hammerlab.guacamole.Main

if [ -z "$CLUSTER" ]; then
	export CLUSTER=guacamole
fi

"$(dirname "${BASH_SOURCE[0]}")"/../dataproc/dataproc "$@"
